[package]
name = "architect-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
architect-core = { path = "../core" }
tracing = { workspace = true }
uuid = { workspace = true }
